[package]
name = "ixv"
version = "0.0.3"
edition = "2021"
description = "A CLI application for verifying intel hex file"
authors = ["Karthik D K <karthikdk1998@gmail.com>"]
categories = ["command-line-utilities"]
keywords = ["intel", "hex"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Karthik-d-k/ixv"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
